name: Rename Image

on:
  push:
    paths:
      - '**/*'
  workflow_dispatch:

jobs:
  rename-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate random 5-letter string
      id: random-string
      run: |
        response=$(curl -s "https://www.random.org/strings/?num=1&len=5&digits=on&loweralpha=on&unique=on&format=plain&rnd=new")
        echo "::set-output name=random-string::${response}"

    - name: Rename image
      run: |
        mv img/image.png img/${{ steps.random-string.outputs.random-string }}.png

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add img/${{ steps.random-string.outputs.random-string }}.png
        git commit -m "Rename image to ${{ steps.random-string.outputs.random-string }}.png"
        git push
