name: Rename Image

on:
  push:
    paths:
      - '**/*'
  workflow_dispatch:

permissions:
  contents: write  # Grant write permission to GITHUB_TOKEN

jobs:
  rename-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate random 5-letter string
      id: random-string
      run: |
        response=$(curl -s "https://www.random.org/strings/?num=1&len=5&digits=on&loweralpha=on&unique=on&format=plain&rnd=new")
        echo "RANDOM_STRING=${response}" >> $GITHUB_ENV

    - name: Rename image
      run: |
        mv img/image.png img/${{ env.RANDOM_STRING }}.png

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add img/${{ env.RANDOM_STRING }}.png
        git commit -m "Rename image to ${{ env.RANDOM_STRING }}.png"
        git push

    - name: Send Discord webhook
      run: |
        IMAGE_URL="https://i2.esb.is-a.dev/${{ env.RANDOM_STRING }}.png"
        PAYLOAD=$(jq -n --arg url "$IMAGE_URL" --arg name "$IMAGE_URL" --argjson color 3447003 '{
          "embeds": [{
            "title": "Renamed Image",
            "description": $url,
            "color": $color,
            "url": $url
          }]
        }')
        curl -H "Content-Type: application/json" \
             -d "$PAYLOAD" \
             ${{ secrets.DISCORD_WEBHOOK_URL }}
